config/routes.rb
DemoApp::Application.routes.draw do
  
  devise_scope :admin do
  get "admin", to: "devise/sessions#new"
  post "admin", to: "desvise/sessions#create"
 
end
  devise_for :admins 
 namespace :admin do 
 resources :articles
 end  
  resources :articles do
    resources :comments
  end

  devise_for :users
  resources :users, only: [:show]
  get 'about' => "home#about"
  root "home#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       if user.class.name == "Admin"
         can :manage, :all
      else
         can :read, :all
         can :update ,Article, :user_id => user.id
       end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable 
        
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :name, presence: true
 #validates :dob, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
 
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, success: 'Article was successfully created.' }
        format.json { render action: 'show', status: :created, location: @article }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, success: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
   def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name,:dob,:email,:password, :password_confirmation) }
  end
   rescue_from CanCan::AccessDenied do |exception|
    flash[:danger] =  exception.message
    redirect_to root_url
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]
  load_and_authorize_resource
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, success: 'Article was successfully created.' }
        format.json { render action: 'show', status: :created, location: @article }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, success: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_article
  def index
    
    @comments = @article.comments
  end
  
  def new
    @comment = @article.comments.new 
  end
  
  def create 
     @comment = @article.comments.new(com_param)
     @comment.name= current_user.name
     if @comment.save
     respond_to do |format|
          format.html { redirect_to @article, success: 'merci pour votre commentaire' }
          format.js
          end
      
       
     end 
  end
  
  private
  def com_param
    params.require(:comment).permit(:name,:content)
  end
  def set_article
    @article =Article.find_by_id(params[:article_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/articles/index.html.haml
%h2 admin index

app/views/articles/_form.html.haml
= form_for @article do |f|
  - if @article.errors.any?
    #error_explanation
      %h2= "#{pluralize(@article.errors.count, "error")} prohibited this article from being saved:"
      %ul
        - @article.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    %br
    = f.text_area :content
  .actions
    = f.submit 'Save'

app/views/articles/edit.html.haml
%h1 Editing article

= render 'form'

= link_to 'Show', @article
\|
= link_to 'Back', articles_path

app/views/articles/index.html.haml
%h1  Articles
= link_to 'New Article', new_article_path
%br
- @articles.each do |article|
  .row
    %div{:class => "col-md-7 col-md-offset-1"}
      %h3 
        =article.title
      %p
        = simple_format(truncate(article.content,length: 50, omission: "..."))
      = link_to 'show', article_path(article)

app/views/articles/new.html.haml
%h1 New article

= render 'form'

= link_to 'Back', articles_path

app/views/articles/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @article.title
%p
  %b Content:
  = @article.content
- if can? :update, @article 
  = link_to 'Edit', edit_article_path(@article)
\|
= link_to 'Back', articles_path
#comments
  = render @article.comments
%br
=render :file => "/comments/new"

    

app/views/comments/_comment.html.haml
= div_for comment do
  = comment.name 
  said :

  %br
  = comment.content
  
   

app/views/comments/create.js.haml
:plain
  $('#comments').append(" #{escape_javascript(render(@comment))} ");
  $('#new_commentaire')[0].reset();

app/views/comments/new.html.haml
=form_for [@article,@article.comments.new],remote: true do |f|
   
  
  %br  
  %label 
    Content
  %br  
    =f.text_area :content
  = f.submit 'Save'

app/views/home/about.html.haml
%h1 About PicBook
%p Find me in app/views/home/about.html.haml

app/views/home/index.html.haml
%h1 Welcome to PicBook
%p Find me in app/views/home/index.html.haml

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .container
   
    %nav
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to "Home", root_path
        
        - if user_signed_in?
          %li 
            = link_to "Articles", articles_path
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              Account
              %b.caret
            %ul.dropdown-menu
              %li
                = link_to "Profile", user_path(current_user)
              %li
                = link_to "Settings", edit_user_registration_path(current_user)
              %li.divider
              %li
                = link_to "Log out", destroy_user_session_path, method: "delete"
        -else
          %li
            = link_to "Log in", new_user_session_path
          %li 
            = link_to "Sign up", new_user_registration_path
        %li
          = link_to "About", about_path
           

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title DemoApp
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = render "layouts/header"
  .container
    - flash.each do |message_type, message|
      .alert{:class=>"alert-#{ message_type}"} 
        = message 
      
    = yield

app/views/users/show.html.haml
%h2 Profile
%h3 put user data here
%p 
  name = 
  =@user.name
%p
  age =
  =@user.dob